export const FETCH_ADVERTS = 'FETCH_ADVERTS';
export const FETCH_ADVERTS_START = 'FETCH_ADVERTS_START';
export const FETCH_ADVERTS_SUCCESS = 'FETCH_ADVERTS_SUCCESS';
export const FETCH_ADVERTS_FAIL = 'FETCH_ADVERTS_FAIL';
