export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const ADD_PRODUCT_TO_FAVORITES = 'ADD_PRODUCT_TO_FAVORITES';
export const REMOVE_PRODUCT_FROM_FAVORITES = 'REMOVE_PRODUCT_FROM_FAVORITES';
export const RETRIEVE_FAVORITES_FROM_LOCALSTORAGE = 'RETRIEVE_FAVORITES_FROM_LOCALSTORAGE';
export const SET_FAVORITES = 'SET_FAVORITES';

export const UPDATE_CATEGORY_FILTER = 'UPDATE_CATEGORY_FILTER';
export const UPDATE_PRICE_FILTER = 'UPDATE_PRICE_FILTER';
export const UPDATE_FAVORITES_ONLY_FILTER = 'UPDATE_ONLY_FAVORITES_FILTER';
