export const FETCH_ADVERTS = 'FETCH_ADVERTS';
export const FETCH_ADVERTS_START = 'FETCH_ADVERTS_START';
export const FETCH_ADVERTS_SUCCESS = 'FETCH_ADVERTS_SUCCESS';
export const FETCH_ADVERTS_FAIL = 'FETCH_ADVERTS_FAIL';

export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_PRICE_FILTER = 'SET_PRICE_FILTER';
export const SET_FAVORITES_ONLY_FILTER = 'SET_ONLY_FAVORITES_FILTER';
